import os

from .providers.tenminuteemail_com import Tenminuteemail_com
from .providers.tenminemail_com import Tenminemail_com
from .providers.tempmail_io import Tempmail_io
from .providers.minuteinbox_com import Minuteinbox_com
from .providers.internxt_com import Internxt_com
from .providers.tempmail_org import Tempmail_org
from .providers.dismailbox_com import Dismailbox_com, Tempmailbox_com
from .providers.tenminutesemail_net import Tenminutesemail_net
from .providers.etempmail_net import Etempmail_net
from .providers.disposablemail_com import Disposablemail_com
from .providers.emailondeck_com import Emailondeck_com
from .providers.onesecmail_com import Onesecmail_com
from .providers.mohmal_com import Mohmal_com, Mohamal_com
from .providers.fakemail_net import Fakemail_net
from .providers.tempmail_email import Tempmail_email
from .providers.tempmail_plus import Tempmail_plus
from .providers.generator_email import Generator_email
from .providers.cryptogmail_com import Cryptogmail_com
from .providers.mail_tm import Mail_tm
from .providers.tempinbox_com import Tempinbox_com
from .providers.mailhole_de import Mailhole_de
from .providers.tmailor_com import Tmailor_com
from .providers.tmail_ai import Tmail_ai
from .providers.cloudtempmail_com import Cloudtempmail_com
from .providers.luxusmail_org import Luxusmail_org
from .providers.muellmail_com import Muellmail_com
from .providers.tempmail_gg import Tempmail_gg
from .providers.eztempmail_com import Eztempmail_com
from .providers.tempail_com import Tempail_com
from .providers.tempmail_ninja import Tempmail_ninja
from .providers.upxmail_com import Upxmail_com
from .providers.trashmail_com import Trashmail_com
from .providers.tempemailfree_com import Tempemailfree_com
from .providers.tempr_email import Tempr_email
from .providers.tempmail_net import Tempmail_net
from .providers.guerillamail_com import Guerillamail_com
from .providers.tmmail_com import Tmmail_com
from .providers.tempmail_lol import Tempmail_lol
from .providers.yopmail_com import Yopmail_com
from .providers.etempmail_com import Etempmail_com
from .providers.tmail_gg import Tmail_gg
from .providers.mailtemp_uk import Mailtemp_uk
from .providers.mostakbile_com import Mostakbile_com
from .providers.fakermail_com import Fakermail_com
from .providers.tempmails_net import Tempmails_net
from .providers.tempdashmail_gg import Tempdashmail_gg
from .providers.adguard_com import Adguard_com
from .providers.maillog_org import Maillog_org
from .providers.wptempmail_com import Wptempmail_com
from .providers.tempmail_id import Tempmail_id
from .providers.zemail_me import Zemail_me
from .providers.tempmailso_com import Tempmailso_com
from .providers.mailtemp_com import Mailtemp_com
from .providers.crazymailing_com import Crazymailing_com
from .providers.fakemailgenerator_com import Fakemailgenerator_com
from .providers.correotemporal_org import Correotemporal_org
from .providers.byom_de import Byom_de
from .providers.moakt_com import Moakt_com
from .providers.inboxes_com import Inboxes_com
from .providers.dropmail_me import Dropmail_me
from .providers.gmailcity_com import Gmailcity_com
from .providers.mailgolem_com import Mailgolem_com
from .providers.anonymmail_net import Anonymmail_net
from .providers.emailfake_com import Emailfake_com
from .providers.disposableemail_co import Disposableemail_co
from .providers.tempinbox_me import Tempinbox_me
from .providers.tempomail_com import Tempomail_com
from .providers.txen_de import Txen_de
from .providers.tempm_com import Tempm_com
from .providers.trashmail_de import Trashmail_de
from .providers.schutzmail_de import Schutzmail_de
from .providers.incognitomail_co import Incognitomail_co
from .providers.tempmailers_com import Tempmailers_com
from .providers.tenminutemail_one import Tenminutemail_one
from .providers.mail_gw import Mail_gw
from .providers.emailtenmin_com import Emailtenmin_com
from .providers.tenminutemail_net import Tenminutemail_net
from .providers.lroid_com import Lroid_com
from .providers.tenminuteemails_com import Tenminuteemails_com
from .providers.maildax_com import Maildax_com
from .providers.tmpmail_co import Tmpmail_co
from .providers.mailsac_com import Mailsac_com
from .providers.fumail_co import Fumail_co
from .providers.tempomail_top import Tempomail_top
from .providers.mail_td import Mail_td
from .providers.mintemail_com import Mintemail_com
from .providers.minutemailbox_com import Minutemailbox_com
from .providers.tmail_io import Tmail_io
from .providers.segamail_com import Segamail_com
from .providers.mailseven_io import Mailseven_io
from .providers.mailfourqa_com import Mailfourqa_com
from .providers.treemail_pro import Treemail_pro
from .providers.getnada_cc import Getnada_cc
from .providers.inboxkitten_com import Inboxkitten_com
from .providers.tempmailinbox_com import Tempmailinbox_com
from .providers.harakirimail_com import Harakirimail_com
from .providers.mailnesia_com import Mailnesia_com
from .providers.mailper_com import Mailper_com
from .providers.mailforspam_com import Mailforspam_com
from .providers.tempemail_co import Tempemail_co
from .providers.tempinbox_xyz import Tempinbox_xyz
from .providers.eyepaste_com import Eyepaste_com
from .providers.emaildashfake_com import Emaildashfake_com
from .providers.rainmail_xyz import Rainmail_xyz
from .providers.mailinator_com import Mailinator_com
from .providers.tempdashmailbox_net import Tempdashmailbox_net
from .providers.expressinboxhub_com import Expressinboxhub_com
from .providers.tempmailbeast_com import Tempmailbeast_com
from .providers.burnermailbox_com import Burnermailbox_com
from .providers.tempemailgen_com import Tempemailgen_com
from .providers.priyo_email import Priyo_email
from .providers.temppmails_com import Temppmails_com
from .providers.fmail_sbs import Fmail_sbs
from .providers.temils_com import Temils_com
from .providers.trashmail_ws import Trashmail_ws
from .providers.tempemail_info import Tempemail_info
from .providers.mailtemp_net import Mailtemp_net
from .providers.haribu_net import Haribu_net
from .providers.mailcatch_com import Mailcatch_com
from .providers.tempmailbox_net import Tempmailbox_net
from .providers.tempmailer_net import Tempmailer_net
from .providers.tempmail_cc import Tempmail_cc

__version__ = "2.1"
__all_providers__ = [os.path.splitext(file_name)[0].capitalize() for file_name in os.listdir(os.path.join(os.path.dirname(__file__), 'providers')) if file_name.endswith(".py")]
__count__ = len(__all_providers__)
